import axios from 'axios';

const BACKEND_URL = import.meta.env.VITE_BACKEND_URL || 'http://127.0.0.1:8000';

const api = axios.create({
  baseURL: BACKEND_URL,
  headers: {
    'Content-Type': 'application/json',
  },
});

export interface ChatResponse {
  ai_response: string;
}

export interface EmailMessage {
  id: string;
  threadId: string;
  snippet: string;
  from: string;
  subject: string;
  date: string;
}

export interface EmailsResponse {
  messages: EmailMessage[];
  nextPageToken?: string;
  resultSizeEstimate: number;
}

// Mock mode for development when backend is not available
let mockMode = false;

export const setMockMode = (enabled: boolean) => {
  mockMode = enabled;
};

export const postChat = async (userPrompt: string, userId?: string): Promise<ChatResponse> => {
  if (mockMode) {
    // Mock response for development
    await new Promise(resolve => setTimeout(resolve, 1000 + Math.random() * 2000));
    return {
      ai_response: `This is a mock response to: "${userPrompt}". In production, this would be generated by your AI backend. The user ID is: ${userId || 'not provided'}.`,
    };
  }

  try {
    const response = await api.post('/chat', {
      user_prompt: userPrompt,
      ...(userId && { user_id: userId }),
    });
    return response.data;
  } catch (error) {
    console.error('Chat API error:', error);
    throw new Error('Failed to send message. Please try again.');
  }
};

export const getEmails = async (userId: string, maxResults: number = 10): Promise<EmailsResponse> => {
  if (mockMode) {
    // Mock email data for development
    await new Promise(resolve => setTimeout(resolve, 1000));
    return {
      messages: [
        {
          id: '199249e03d01e039',
          threadId: '199249e03d01e039',
          snippet: 'Hello — let\'s meet to discuss the project...',
          from: 'alice@example.com',
          subject: 'Project Meeting',
          date: '2025-09-01T12:34:00Z',
        },
        {
          id: '199249e03d01e040',
          threadId: '199249e03d01e040',
          snippet: 'Thank you for your presentation yesterday...',
          from: 'bob@company.com',
          subject: 'Follow-up',
          date: '2025-08-31T15:22:00Z',
        },
        {
          id: '199249e03d01e041',
          threadId: '199249e03d01e041',
          snippet: 'Reminder: Team standup at 10 AM tomorrow...',
          from: 'team@company.com',
          subject: 'Daily Standup Reminder',
          date: '2025-08-30T18:45:00Z',
        },
      ],
      nextPageToken: 'abc123',
      resultSizeEstimate: 201,
    };
  }

  try {
    const response = await api.get('/emails', {
      params: { user_id: userId, max_results: maxResults },
    });
    return response.data;
  } catch (error) {
    console.error('Emails API error:', error);
    throw new Error('Failed to fetch emails. Please try again.');
  }
};

export const notifyConnection = async (userId: string): Promise<{ ok: boolean }> => {
  if (mockMode) {
    await new Promise(resolve => setTimeout(resolve, 500));
    return { ok: true };
  }

  try {
    const response = await api.post('/notify-connection', { user_id: userId });
    return response.data;
  } catch (error) {
    console.error('Notify connection API error:', error);
    throw new Error('Failed to notify backend of Gmail connection.');
  }
};